[package]
name = "topology"
version = "0.1.0"
edition.workspace = true

[dependencies]
snafu.workspace = true
superblock.workspace = true
nix.workspace = true
log.workspace = true
gpt.workspace = true
fs-err.workspace = true
