[package]
name = "topology"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
superblock = { path = "../superblock" }
nix.workspace = true
log.workspace = true
gpt = "3.1.0"